// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BunnyApiClient.Models.PullZone
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.16.0")]
    #pragma warning disable CS1591
    public enum PullZoneCreate_RoutingFilters
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "all")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
        [EnumMember(Value = "eu")]
        #pragma warning disable CS1591
        Eu,
        #pragma warning restore CS1591
    }
}
