// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.Extensions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace StreamApiClient.OEmbed
{
    /// <summary>
    /// Builds and executes requests for operations under \OEmbed
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
    public partial class OEmbedRequestBuilder : BaseCliRequestBuilder
    {
        /// <summary>
        /// [OEmbed API Docs](https://docs.bunny.net/reference/oembed_getoembed)
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildGetCommand()
        {
            var command = new Command("get");
            command.Description = "[OEmbed API Docs](https://docs.bunny.net/reference/oembed_getoembed)";
            var urlOption = new Option<string>("--url") {
            };
            urlOption.IsRequired = false;
            command.AddOption(urlOption);
            var maxWidthOption = new Option<int?>("--max-width") {
            };
            maxWidthOption.IsRequired = false;
            command.AddOption(maxWidthOption);
            var maxHeightOption = new Option<int?>("--max-height") {
            };
            maxHeightOption.IsRequired = false;
            command.AddOption(maxHeightOption);
            var tokenOption = new Option<string>("--token") {
            };
            tokenOption.IsRequired = false;
            command.AddOption(tokenOption);
            var expiresOption = new Option<long?>("--expires") {
            };
            expiresOption.IsRequired = true;
            command.AddOption(expiresOption);
            var outputOption = new Option<FormatterType>("--output", () => FormatterType.JSON);
            command.AddOption(outputOption);
            var queryOption = new Option<string>("--query");
            command.AddOption(queryOption);
            command.SetHandler(async (invocationContext) => {
                var url = invocationContext.ParseResult.GetValueForOption(urlOption);
                var maxWidth = invocationContext.ParseResult.GetValueForOption(maxWidthOption);
                var maxHeight = invocationContext.ParseResult.GetValueForOption(maxHeightOption);
                var token = invocationContext.ParseResult.GetValueForOption(tokenOption);
                var expires = invocationContext.ParseResult.GetValueForOption(expiresOption);
                var output = invocationContext.ParseResult.GetValueForOption(outputOption);
                var query = invocationContext.ParseResult.GetValueForOption(queryOption);
                IOutputFilter outputFilter = invocationContext.BindingContext.GetService(typeof(IOutputFilter)) as IOutputFilter ?? throw new ArgumentNullException("outputFilter");
                IOutputFormatterFactory outputFormatterFactory = invocationContext.BindingContext.GetService(typeof(IOutputFormatterFactory)) as IOutputFormatterFactory ?? throw new ArgumentNullException("outputFormatterFactory");
                var cancellationToken = invocationContext.GetCancellationToken();
                var reqAdapter = invocationContext.GetRequestAdapter();
                var requestInfo = ToGetRequestInformation(q => {
                    if (!string.IsNullOrEmpty(url)) q.QueryParameters.Url = url;
                    q.QueryParameters.MaxWidth = maxWidth;
                    q.QueryParameters.MaxHeight = maxHeight;
                    if (!string.IsNullOrEmpty(token)) q.QueryParameters.Token = token;
                    q.QueryParameters.Expires = expires;
                });
                var response = await reqAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping: default, cancellationToken: cancellationToken) ?? Stream.Null;
                response = (response != Stream.Null) ? await outputFilter.FilterOutputAsync(response, query, cancellationToken) : response;
                var formatter = outputFormatterFactory.GetFormatter(output);
                await formatter.WriteOutputAsync(response, cancellationToken);
            });
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StreamApiClient.OEmbed.OEmbedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public OEmbedRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/OEmbed?expires={expires}{&maxHeight,maxWidth,token,url}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::StreamApiClient.OEmbed.OEmbedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public OEmbedRequestBuilder(string rawUrl) : base("{+baseurl}/OEmbed?expires={expires}{&maxHeight,maxWidth,token,url}", rawUrl)
        {
        }
        /// <summary>
        /// [OEmbed API Docs](https://docs.bunny.net/reference/oembed_getoembed)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::StreamApiClient.OEmbed.OEmbedRequestBuilder.OEmbedRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::StreamApiClient.OEmbed.OEmbedRequestBuilder.OEmbedRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// [OEmbed API Docs](https://docs.bunny.net/reference/oembed_getoembed)
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.18.0")]
        public partial class OEmbedRequestBuilderGetQueryParameters 
        {
            [QueryParameter("expires")]
            public long? Expires { get; set; }
            [QueryParameter("maxHeight")]
            public int? MaxHeight { get; set; }
            [QueryParameter("maxWidth")]
            public int? MaxWidth { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("token")]
            public string? Token { get; set; }
#nullable restore
#else
            [QueryParameter("token")]
            public string Token { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("url")]
            public string? Url { get; set; }
#nullable restore
#else
            [QueryParameter("url")]
            public string Url { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
