// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace StreamApiClient.Models.ManageCollections
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Collection : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unique ID of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Guid { get; private set; }
#nullable restore
#else
        public string Guid { get; private set; }
#endif
        /// <summary>The name of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The URLs of preview images of videos in the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewImageUrls { get; private set; }
#nullable restore
#else
        public string PreviewImageUrls { get; private set; }
#endif
        /// <summary>The IDs of videos to be used as preview icons</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviewVideoIds { get; private set; }
#nullable restore
#else
        public string PreviewVideoIds { get; private set; }
#endif
        /// <summary>The total storage size of the collection</summary>
        public long? TotalSize { get; private set; }
        /// <summary>The number of videos that the collection contains</summary>
        public long? VideoCount { get; private set; }
        /// <summary>The video library ID that contains the collection</summary>
        public long? VideoLibraryId { get; private set; }
        /// <summary>
        /// Instantiates a new <see cref="global::StreamApiClient.Models.ManageCollections.Collection"/> and sets the default values.
        /// </summary>
        public Collection()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::StreamApiClient.Models.ManageCollections.Collection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::StreamApiClient.Models.ManageCollections.Collection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::StreamApiClient.Models.ManageCollections.Collection();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "guid", n => { Guid = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "previewImageUrls", n => { PreviewImageUrls = n.GetStringValue(); } },
                { "previewVideoIds", n => { PreviewVideoIds = n.GetStringValue(); } },
                { "totalSize", n => { TotalSize = n.GetLongValue(); } },
                { "videoCount", n => { VideoCount = n.GetLongValue(); } },
                { "videoLibraryId", n => { VideoLibraryId = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
