// <auto-generated/>
#pragma warning disable CS0618
using BunnyApiClient.Billing.Affiliate;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System;
namespace BunnyApiClient.Billing
{
    /// <summary>
    /// Builds and executes requests for operations under \billing
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BillingRequestBuilder : BaseCliRequestBuilder
    {
        /// <summary>
        /// The affiliate property
        /// </summary>
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildAffiliateNavCommand()
        {
            var command = new Command("affiliate");
            command.Description = "The affiliate property";
            var builder = new global::BunnyApiClient.Billing.Affiliate.AffiliateRequestBuilder(PathParameters);
            var execCommands = new List<Command>();
            var nonExecCommands = new List<Command>();
            nonExecCommands.Add(builder.BuildClaimNavCommand());
            execCommands.Add(builder.BuildGetCommand());
            foreach (var cmd in execCommands)
            {
                command.AddCommand(cmd);
            }
            foreach (var cmd in nonExecCommands)
            {
                command.AddCommand(cmd);
            }
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Billing.BillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public BillingRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/billing", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Billing.BillingRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public BillingRequestBuilder(string rawUrl) : base("{+baseurl}/billing", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
