// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace BunnyApiClient.Models.Search.GlobalSearch
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GlobalSearchType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cdn")]
        #pragma warning disable CS1591
        Cdn,
        #pragma warning restore CS1591
        [EnumMember(Value = "storage")]
        #pragma warning disable CS1591
        Storage,
        #pragma warning restore CS1591
        [EnumMember(Value = "dns")]
        #pragma warning disable CS1591
        Dns,
        #pragma warning restore CS1591
        [EnumMember(Value = "script")]
        #pragma warning disable CS1591
        Script,
        #pragma warning restore CS1591
        [EnumMember(Value = "stream")]
        #pragma warning disable CS1591
        Stream,
        #pragma warning restore CS1591
    }
}
