// <auto-generated/>
#pragma warning disable CS0618
using BunnyApiClient.Models.Shield;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Cli.Commons.Extensions;
using Microsoft.Kiota.Cli.Commons.IO;
using Microsoft.Kiota.Cli.Commons;
using System.Collections.Generic;
using System.CommandLine;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace BunnyApiClient.Shield.Metrics.Waf.Processed.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \shield\metrics\waf\processed\{shieldZoneId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithShieldZoneItemRequestBuilder : BaseCliRequestBuilder
    {
        /// <returns>A <see cref="Command"/></returns>
        public Command BuildGetCommand()
        {
            var command = new Command("get");
            var shieldZoneIdOption = new Option<int?>("--shield-zone-id") {
            };
            shieldZoneIdOption.IsRequired = true;
            command.AddOption(shieldZoneIdOption);
            var dataTimeframeOption = new Option<int?>("--data-timeframe") {
            };
            dataTimeframeOption.IsRequired = false;
            command.AddOption(dataTimeframeOption);
            var groupTimeOption = new Option<string>("--group-time") {
            };
            groupTimeOption.IsRequired = false;
            command.AddOption(groupTimeOption);
            var outputOption = new Option<FormatterType>("--output", () => FormatterType.JSON);
            command.AddOption(outputOption);
            var queryOption = new Option<string>("--query");
            command.AddOption(queryOption);
            command.SetHandler(async (invocationContext) => {
                var shieldZoneId = invocationContext.ParseResult.GetValueForOption(shieldZoneIdOption);
                var dataTimeframe = invocationContext.ParseResult.GetValueForOption(dataTimeframeOption);
                var groupTime = invocationContext.ParseResult.GetValueForOption(groupTimeOption);
                var output = invocationContext.ParseResult.GetValueForOption(outputOption);
                var query = invocationContext.ParseResult.GetValueForOption(queryOption);
                IOutputFilter outputFilter = invocationContext.BindingContext.GetService(typeof(IOutputFilter)) as IOutputFilter ?? throw new ArgumentNullException("outputFilter");
                IOutputFormatterFactory outputFormatterFactory = invocationContext.BindingContext.GetService(typeof(IOutputFormatterFactory)) as IOutputFormatterFactory ?? throw new ArgumentNullException("outputFormatterFactory");
                var cancellationToken = invocationContext.GetCancellationToken();
                var reqAdapter = invocationContext.GetRequestAdapter();
                var requestInfo = ToGetRequestInformation(q => {
                    q.QueryParameters.DataTimeframe = dataTimeframe;
                    if (!string.IsNullOrEmpty(groupTime)) q.QueryParameters.GroupTime = groupTime;
                });
                if (shieldZoneId is not null) requestInfo.PathParameters.Add("shieldZoneId", shieldZoneId);
                var errorMapping = new Dictionary<string, ParsableFactory<IParsable>> {
                    {"401", UnauthorizedResult.CreateFromDiscriminatorValue},
                };
                var response = await reqAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping: errorMapping, cancellationToken: cancellationToken) ?? Stream.Null;
                response = (response != Stream.Null) ? await outputFilter.FilterOutputAsync(response, query, cancellationToken) : response;
                var formatter = outputFormatterFactory.GetFormatter(output);
                await formatter.WriteOutputAsync(response, cancellationToken);
            });
            return command;
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.Metrics.Waf.Processed.Item.WithShieldZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        public WithShieldZoneItemRequestBuilder(Dictionary<string, object> pathParameters) : base("{+baseurl}/shield/metrics/waf/processed/{shieldZoneId}{?dataTimeframe,groupTime}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::BunnyApiClient.Shield.Metrics.Waf.Processed.Item.WithShieldZoneItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public WithShieldZoneItemRequestBuilder(string rawUrl) : base("{+baseurl}/shield/metrics/waf/processed/{shieldZoneId}{?dataTimeframe,groupTime}", rawUrl)
        {
        }
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BunnyApiClient.Shield.Metrics.Waf.Processed.Item.WithShieldZoneItemRequestBuilder.WithShieldZoneItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::BunnyApiClient.Shield.Metrics.Waf.Processed.Item.WithShieldZoneItemRequestBuilder.WithShieldZoneItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json, text/plain;q=0.9");
            return requestInfo;
        }
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        #pragma warning disable CS1591
        public partial class WithShieldZoneItemRequestBuilderGetQueryParameters 
        #pragma warning restore CS1591
        {
            [QueryParameter("dataTimeframe")]
            public int? DataTimeframe { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("groupTime")]
            public string? GroupTime { get; set; }
#nullable restore
#else
            [QueryParameter("groupTime")]
            public string GroupTime { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
